# Generated by Django 4.2 on 2023-07-24 10:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'ordering': ('date_added',)},
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='uploads/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mkv'])])),
                ('thumbnail', models.ImageField(blank=True, upload_to='uploads/thumbnails/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.category')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
