# Generated by Django 4.2 on 2023-07-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_main_options_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-date_added',)},
        ),
    ]
