# Generated by Django 5.0.1 on 2024-02-03 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_main_options_alter_video_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Կատեգորիա",
                "verbose_name_plural": "Կատեգորիա",
            },
        ),
        migrations.AlterModelOptions(
            name="main",
            options={
                "ordering": ("-date_added",),
                "verbose_name": "Հոդված",
                "verbose_name_plural": "Հոդված",
            },
        ),
        migrations.AlterModelOptions(
            name="video",
            options={
                "ordering": ("-date_added",),
                "verbose_name": "Տեսանյութներ",
                "verbose_name_plural": "Տեսանյութներ",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Անուն"),
        ),
        migrations.AlterField(
            model_name="main",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="նյութի ներբեռման ժամանակ"
            ),
        ),
        migrations.AlterField(
            model_name="main",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Վերնագիր"),
        ),
        migrations.AlterField(
            model_name="video",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Ներբեռման ժամանակ"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Անուն"),
        ),
        migrations.CreateModel(
            name="VideoY",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("youtube_id", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videoY",
                        to="main.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Տեսանյութներ",
                "verbose_name_plural": "Տեսանյութներ",
                "ordering": ("-published_at",),
            },
        ),
    ]
