# Generated by Django 4.2 on 2024-02-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_video_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Գրառում հրապարակված է'),
        ),
    ]
