# Generated by Django 4.2 on 2024-02-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_main_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Գրառում հրապարակված է'),
        ),
    ]
