# Generated by Django 4.2 on 2024-03-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
