# Generated by Django 4.2 on 2024-03-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_main_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='link_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Լինկի Վերնագիր'),
        ),
    ]
