# Generated by Django 5.1 on 2024-08-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_reclam_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclam",
            name="slug",
            field=models.SlugField(default=1),
        ),
    ]
