# Generated by Django 5.0.1 on 2024-08-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_reclam_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclam',
            options={'ordering': ('-published',), 'verbose_name': 'Գովազդ', 'verbose_name_plural': 'Գովազդ'},
        ),
    ]
